Show GIVback amount at distribute time
Giveth/liquidity-mining-dapp pull request #113
Opened 2022-01-05 14:14 UTC by MohammadPCh

2022-01-05 14:38 UTC, aminlatifi requested changes
In harvest modal also we should show the `givbackLiquidPart` (the liquid amount at the moment givback is paid)

2022-01-05 14:38 UTC, aminlatifi commented on src/components/homeTabs/GIVbacks.tsx
> +	console.log(`balances`, balances);
Please remove these console.log lines

2022-01-06 07:48 UTC, MohammadPCh commented
@aminlatifi it's ready for review.
Thanks

2022-01-06 10:13 UTC, aminlatifi commented
LGTM!

2022-01-06 10:13 UTC, merged