Harvest modal when unstaking NFT
Giveth/liquidity-mining-dapp pull request #68
Opened 2021-12-21 21:18 UTC by pkretzschmar

2021-12-22 18:14 UTC, mendesfabio commented on src/components/modals/V3Stake.tsx
> +			console.log('as');
```suggestion
```

2021-12-23 13:50 UTC, aminlatifi requested changes
I had to merge develop into it because we had changed nft info fetching drastically.

2021-12-23 13:50 UTC, aminlatifi commented on src/hooks/useStakingNFT.tsx
> -			try {
Let's keep it as it was and calculate all rewards here. For the info for harvest modal on exit, we can make another call since it happens rarely.

2021-12-23 20:50 UTC, pkretzschmar commented
The reward now is working and is being called when the user wants to untsake an NFT. The only "problem" is that sometimes the reward is so small that the numbers are rounded to 0.

2021-12-24 11:11 UTC, aminlatifi commented
LGTM!

2021-12-24 11:11 UTC, aminlatifi commented
Thanks @mendesfabio @pkretzschmar

2021-12-24 11:12 UTC, merged